#!/usr/bin/env bash

brew install neovim
brew install ripgrep
brew install fzf
brew install fd
brew install tmux
brew install node
brew install go
brew install delve
brew install cmake
brew install gh
brew install golangci-lint
brew install goose
brew install sqlc
brew install sst/tap/opencode
brew install protobuf
brew install python@3.13
brew install 1password-cli
brew install postgresql@17
brew install --cask displaylink
brew install --cask postman
brew install --cask raycast
brew install --cask beekeeper-studio
brew install --cask unnaturalscrollwheels
brew install --cask visual-studio-code
brew install --cask vivaldi
brew install --cask yt-music
brew install --cask ghostty
